//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baikt
{
    using System;
    using System.Collections.Generic;
    
    public partial class qlsv
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Khoa { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<double> Diem1 { get; set; }
        public Nullable<double> Diem2 { get; set; }
        public Nullable<double> Diem3 { get; set; }
        public Nullable<double> Diem4 { get; set; }
    }
}
